import { Link } from '@inertiajs/react';
import WorkspaceLayout from '../../../Layouts/WorkspaceLayout';
import { Action, Editor, Field, Panel, Pagination, Status, Table, field, label, options, useWorkspace } from '../../../Components/Workspace/UI';
import { useState } from 'react';
function SectionEditor({composition:c,section,registry,eligibleMedia,newType}) {
 const {t}=useWorkspace();const v=section?.current_version;const type=v?.type??newType;const definition=registry[type];const content=Object.fromEntries(definition.fields.map(key=>[key,key==='items'?JSON.stringify(v?.content?.[key]??[],null,2):v?.content?.[key]??'']));
 const initial={lock_version:c.lock_version,type,variant:v?.variant??definition.default_variant,editor_label:section?.editor_label??'',enabled:v?.enabled??true,visibility_rule:v?.visibility_rule??'always',visible_from:v?.visible_from?.slice(0,16)??'',visible_until:v?.visible_until?.slice(0,16)??'',selection_mode:v?.selection_mode??'',maximum_items:v?.maximum_items??'',media_selection_present:true,media_asset_ids:(v?.media??[]).map(m=>String(m.media_asset_id)),...Object.fromEntries(Object.entries(content).map(([k,value])=>[`content_${k}`,value])),...Object.fromEntries(Object.entries(v?.presentation??{surface_tone:'default',container_width:'standard',spacing_top:'standard'}).map(([k,value])=>[`presentation_${k}`,value]))};
 const transform=data=>{const result={},content={},presentation={};Object.entries(data).forEach(([k,value])=>{if(k.startsWith('content_'))content[k.slice(8)]=value;else if(k.startsWith('presentation_'))presentation[k.slice(13)]=value;else result[k]=value;});return {...result,content,presentation};};
 return <Editor action={`/admin/page-compositions/${c.id}/sections${section?'/'+section.id:''}`} method={section?'patch':'post'} initial={initial} transform={transform} fields={[field('editor_label','Editor label','text',{required:true}),field('variant','Variant','select',{options:definition.variants}),...definition.fields.map(key=>field(`content_${key}`,label(key),['items','body','summary','quote'].includes(key)?'textarea':'text',{required:definition.required.includes(key)})),field('enabled','Enabled','checkbox'),field('visibility_rule','Visibility rule','select',{options:['always','scheduled','when_populated']}),field('visible_from','Visible from','datetime-local'),field('visible_until','Visible until','datetime-local'),...(definition.relations.length?[field('selection_mode','Content selection','select',{options:['','manual','featured','latest','related','category']}),field('maximum_items','Maximum items','number',{min:1,max:24})]:[]),...(definition.media.length?[field('media_asset_ids','Approved media','select',{options:options(eligibleMedia,'title'),multiple:true})]:[])]} submit={section?'Save section':'Add section'}>{form=><details><summary>{t('Presentation')}</summary><div className="grid gap-4 mt-4">{Object.keys(initial).filter(k=>k.startsWith('presentation_')).map(k=><Field key={k} form={form} name={k} label={label(k.slice(13))}/>)}</div></details>}</Editor>;
}
export default function Edit({composition:c,registry,previewUrl,eligibleMedia,archivedSections=[]}) {
 const {t,can}=useWorkspace();const [type,setType]=useState(Object.keys(registry)[0]);const editable=c.editable&&can('pages.update');
 const transitionMap={draft:['pages.update',['in_review']],changes_requested:['pages.update',['in_review']],in_review:['pages.approve',['changes_requested','approved']],approved:['pages.publish',['scheduled','published']],scheduled:['pages.publish',['published','archived']],published:['pages.publish',['archived']]};const transition=transitionMap[c.state];const destinations=transition&&can(transition[0])?transition[1]:[];
 const reorder=(index,offset)=>{const ids=c.sections.map(s=>s.id);[ids[index],ids[index+offset]]=[ids[index+offset],ids[index]];return {lock_version:c.lock_version,section_ids:ids};};
 return <WorkspaceLayout title={label(c.page_key)} actions={<><a className="button-secondary" href={previewUrl} target="_blank" rel="noreferrer">{t('Secure preview')}</a>{!c.editable&&can('pages.create')&&<Action href={`/admin/page-compositions/${c.id}/drafts`}>{t('Create editable draft')}</Action>}</>}><Panel><div className="flex flex-wrap gap-5"><Status value={c.state}/><p>{c.locale.toUpperCase()} · v{c.version_no} · {t('Edit lock')}: {c.lock_version}</p></div></Panel>{!c.editable&&<p className="status-information">{t('Published version is read-only')}</p>}{editable&&<details className="admin-panel"><summary className="font-bold">{t('Add controlled section')}</summary><label className="form-label mt-4" htmlFor="new-section-type">{t('Section type')}</label><select id="new-section-type" className="form-input mb-5" value={type} onChange={e=>setType(e.target.value)}>{Object.entries(registry).map(([value,d])=><option key={value} value={value}>{t(d.name)}</option>)}</select><SectionEditor key={`${type}-${c.lock_version}`} composition={c} registry={registry} eligibleMedia={eligibleMedia} newType={type}/></details>}<div className="grid gap-5">{c.sections.map((section,index)=><Panel key={`${section.id}-${c.lock_version}`} title={section.editor_label}>{editable?<><SectionEditor composition={c} section={section} registry={registry} eligibleMedia={eligibleMedia}/><div className="mt-5 flex flex-wrap gap-3">{index>0&&<Action href={`/admin/page-compositions/${c.id}/sections/order`} method="put" data={reorder(index,-1)}>{t('Move up')}</Action>}{index<c.sections.length-1&&<Action href={`/admin/page-compositions/${c.id}/sections/order`} method="put" data={reorder(index,1)}>{t('Move down')}</Action>}<Action href={`/admin/page-compositions/${c.id}/sections/${section.id}/duplicate`} data={{lock_version:c.lock_version}}>{t('Duplicate')}</Action>{can('pages.delete')&&!section.required&&!section.locked&&<Action href={`/admin/page-compositions/${c.id}/sections/${section.id}`} method="delete" data={{lock_version:c.lock_version}} confirm="Archive this section?">{t('Archive')}</Action>}</div></>:<div className="whitespace-pre-wrap">{Object.values(section.current_version?.content??{}).filter(v=>typeof v==='string').join('\n\n')}</div>}</Panel>)}</div>{editable&&archivedSections.length>0&&<Panel title={t('Archived sections')}>{archivedSections.map(s=><div key={s.id} className="flex gap-4 py-3"><span>{s.editor_label}</span><Action href={`/admin/page-compositions/${c.id}/sections/${s.id}/restore`} data={{lock_version:c.lock_version}}>{t('Restore')}</Action></div>)}</Panel>}{destinations.length>0&&<Panel title={t('Page controls')}><Editor key={c.state} action={`/admin/page-compositions/${c.id}/transitions`} initial={{to:destinations[0],comment:''}} fields={[field('to','Workflow action','select',{options:destinations}),field('comment','Review comment','textarea')]} submit="Apply workflow action"/></Panel>}</WorkspaceLayout>;
}
