import { Link, router } from '@inertiajs/react';
import { useState } from 'react';
import WorkspaceLayout from '../../../Layouts/WorkspaceLayout';
import { Action, Editor, Field, field, label, options, useWorkspace } from '../../../Components/Workspace/UI';
import { canPublishPage, localeLabel } from './Index';

function SectionEditor({composition:c,section,registry,eligibleMedia,newType,onDirtyChange}) {
 const {t}=useWorkspace();
 const v=section?.current_version, type=v?.type??newType, definition=registry[type];
 const content=Object.fromEntries(definition.fields.map(key=>[key,key==='items'?JSON.stringify(v?.content?.[key]??[],null,2):v?.content?.[key]??'']));
 const initial={lock_version:c.lock_version,type,variant:v?.variant??definition.default_variant,editor_label:section?.editor_label??'',enabled:v?.enabled??true,visibility_rule:v?.visibility_rule??'always',visible_from:v?.visible_from?.slice(0,16)??'',visible_until:v?.visible_until?.slice(0,16)??'',selection_mode:v?.selection_mode??'',maximum_items:v?.maximum_items??'',media_selection_present:true,media_asset_ids:(v?.media??[]).map(m=>String(m.media_asset_id)),...Object.fromEntries(Object.entries(content).map(([k,value])=>[`content_${k}`,value])),...Object.fromEntries(Object.entries(v?.presentation??{surface_tone:'default',container_width:'standard',spacing_top:'standard'}).map(([k,value])=>[`presentation_${k}`,value]))};
 const transform=data=>{const result={},content={},presentation={};Object.entries(data).forEach(([k,value])=>{if(k.startsWith('content_'))content[k.slice(8)]=value;else if(k.startsWith('presentation_'))presentation[k.slice(13)]=value;else result[k]=value;});return {...result,content,presentation};};
 const advanced=[...(section?[field('editor_label','Editor label','text',{required:true})]:[]),field('variant','Variant','select',{options:definition.variants}),field('visibility_rule','Visibility rule','select',{options:['always','scheduled','when_populated']}),field('visible_from','Visible from','datetime-local'),field('visible_until','Visible until','datetime-local'),...(definition.relations.length?[field('selection_mode','Content selection','select',{options:['','manual','featured','latest','related','category']}),field('maximum_items','Maximum items','number',{min:1,max:24})]:[])];
 const basic=[...(!section?[field('editor_label','Section name','text',{required:true})]:[]),...definition.fields.map(key=>field(`content_${key}`,label(key),['items','body','summary','quote'].includes(key)?'textarea':'text',{required:definition.required.includes(key)})),...(definition.media.length?[field('media_asset_ids','Approved media','select',{options:options(eligibleMedia,'title'),multiple:true})]:[]),field('enabled','Show this section','checkbox')];
 return <Editor action={`/admin/page-compositions/${c.id}/sections${section?'/'+section.id:''}`} method={section?'patch':'post'} initial={initial} transform={transform} onDirtyChange={onDirtyChange} fields={basic} submit={section?'Save section':'Add section'}>{form=><details className="workspace-advanced" open={advanced.some(f=>form.errors[f.name])||Object.keys(form.errors).some(key=>key.startsWith('presentation'))}><summary>{t('Advanced settings')}</summary><p className="form-help mt-3">{t('Optional layout, scheduling and content selection settings.')}</p><div className="grid gap-4 mt-4">{advanced.map(f=><Field key={f.name} form={form} {...f}/>)}{Object.keys(initial).filter(k=>k.startsWith('presentation_')).map(k=><Field key={k} form={form} name={k} label={label(k.slice(13))}/>)}</div></details>}</Editor>;
}
const transitions={draft:['pages.update',['in_review']],changes_requested:['pages.update',['in_review']],in_review:['pages.approve',['changes_requested','approved']],approved:['pages.publish',['scheduled','published']],scheduled:['pages.publish',['published','archived']],published:['pages.publish',['archived']]};
const workflowLabels={in_review:'Submit for review',changes_requested:'Request changes',approved:'Approve page',scheduled:'Schedule publication',published:'Publish now',archived:'Archive page'};
export default function Edit(props) {return <CompositionEditor key={props.composition.id} {...props}/>;}
function CompositionEditor({composition:c,registry,previewUrl,eligibleMedia,archivedSections=[],pageVersions=[]}) {
 const {t,can}=useWorkspace();
 const [type,setType]=useState(Object.keys(registry)[0]);
 const [dirty,setDirty]=useState({}), [pendingHref,setPendingHref]=useState(null);
 const editable=c.editable&&can('pages.update');
 const unsavedSections=Object.entries(dirty).some(([key,value])=>key!=='workflow'&&value);
 const reportDirty=(key,value)=>setDirty(current=>current[key]===value?current:{...current,[key]:value});
 const leave=visit=>{if(!Object.values(dirty).some(Boolean))return true;setPendingHref(visit.url.href);return false;};
 const versions=pageVersions.filter(version=>version.locale===c.locale);
 const transition=transitions[c.state], destinations=transition&&can(transition[0])?transition[1]:[];
 const reorder=(index,offset)=>{const ids=c.sections.map(s=>s.id);[ids[index],ids[index+offset]]=[ids[index+offset],ids[index]];return {lock_version:c.lock_version,section_ids:ids};};
 return <WorkspaceLayout title={label(c.page_key)} description="Open a section, then save your changes." actions={<><a className="button-secondary" href={previewUrl} target="_blank" rel="noreferrer">{t('Preview page')}</a>{!c.editable&&can('pages.create')&&<Action href={`/admin/page-compositions/${c.id}/drafts`} className="button-primary">{t('Edit this page')}</Action>}</>}>
  <Link className="text-link" href="/admin/page-compositions" onBefore={leave}>{t('Back to website pages')}</Link>
  {pendingHref&&<div className="status-warning" role="alert"><p>{t('You have unsaved changes. Leave without saving?')}</p><div className="mt-3 flex flex-wrap gap-3"><button className="button-secondary" onClick={()=>setPendingHref(null)}>{t('Keep editing')}</button><button className="button-primary" onClick={()=>{setPendingHref(null);router.visit(pendingHref);}}>{t('Discard changes')}</button></div></div>}
  <div className="workspace-page-status"><strong>{t(label(c.state))}</strong><span>{localeLabel(c.locale)}</span><span>{c.sections.length} {t('Sections')}</span></div>
  {!c.editable&&<p className="status-information">{t('Published version is read-only')}</p>}
  {canPublishPage(c.state,can)&&<section className="admin-panel"><div className="flex flex-wrap items-center justify-between gap-5"><div><h2 className="heading-3">{t('Ready to go live?')}</h2><p className="form-help">{t(unsavedSections?'Save your section changes first, then publish.':'Publish your saved changes to the website in one click.')}</p></div><Editor key={c.lock_version} action={`/admin/page-compositions/${c.id}/publish`} initial={{lock_version:c.lock_version}} disabled={unsavedSections} submit="Publish now" /></div></section>}
  <section aria-labelledby="page-sections-title"><h2 id="page-sections-title" className="heading-3 mb-4">{t('Page sections')}</h2><p className="text-sm text-muted mb-4">{t('Open only the section you want to change.')}</p><div className="grid gap-4">
   {c.sections.map((section,index)=><details className="admin-panel workspace-section-editor" key={`${section.id}-${c.lock_version}`} open={index===0}><summary><span className="workspace-section-number">{index+1}</span><span>{section.editor_label}</span><span className="workspace-section-type">{t(registry[section.current_version?.type]?.name??'Section')}</span></summary><div className="pt-5">{editable?<>
    <SectionEditor composition={c} section={section} registry={registry} eligibleMedia={eligibleMedia} onDirtyChange={value=>reportDirty(section.id,value)}/>
    <details className="workspace-advanced mt-5"><summary>{t('Section actions')}</summary><div className="mt-4 flex flex-wrap gap-3">{index>0&&<Action href={`/admin/page-compositions/${c.id}/sections/order`} method="put" data={reorder(index,-1)}>{t('Move up')}</Action>}{index<c.sections.length-1&&<Action href={`/admin/page-compositions/${c.id}/sections/order`} method="put" data={reorder(index,1)}>{t('Move down')}</Action>}<Action href={`/admin/page-compositions/${c.id}/sections/${section.id}/duplicate`} data={{lock_version:c.lock_version}}>{t('Duplicate')}</Action>{can('pages.delete')&&!section.required&&!section.locked&&<Action href={`/admin/page-compositions/${c.id}/sections/${section.id}`} method="delete" data={{lock_version:c.lock_version}} confirm="Archive this section?">{t('Archive')}</Action>}</div></details>
   </>:<div className="whitespace-pre-wrap">{Object.values(section.current_version?.content??{}).filter(v=>typeof v==='string').join('\n\n')}</div>}</div></details>)}
   {!c.sections.length&&<p className="empty-state">{t('No sections yet. Add a section to start building this page.')}</p>}
  </div></section>
  {editable&&<details className="admin-panel"><summary className="font-semibold">{t('Add a section')}</summary><label className="form-label mt-4" htmlFor="new-section-type">{t('Section type')}</label><select id="new-section-type" className="form-input mb-5" value={type} onChange={e=>setType(e.target.value)}>{Object.entries(registry).map(([value,d])=><option key={value} value={value}>{t(d.name)}</option>)}</select><SectionEditor key={`${type}-${c.lock_version}`} composition={c} registry={registry} eligibleMedia={eligibleMedia} newType={type} onDirtyChange={value=>reportDirty('new',value)}/></details>}
  {destinations.length>0&&<details className="admin-panel"><summary className="font-semibold">{t('Review, scheduling and archive options')}</summary><p className="text-sm text-muted mb-5">{t('Save your sections before sending this page to the next step.')}</p><Editor key={c.state} disabled={unsavedSections} action={`/admin/page-compositions/${c.id}/transitions`} initial={{to:destinations[0],comment:''}} onDirtyChange={value=>reportDirty('workflow',value)} fields={[field('to','Next step','select',{options:destinations.map(value=>({value,label:workflowLabels[value]}))}),field('comment','Review comment','textarea')]} submit="Continue">{unsavedSections&&<p className="status-warning" role="status">{t('Save your sections before sending this page to the next step.')}</p>}</Editor></details>}
  {(versions.length>1||archivedSections.length>0)&&<details className="admin-panel"><summary className="font-semibold">{t('History and archived sections')}</summary><div className="grid gap-5 mt-5">
   {versions.length>1&&<div><h2 className="font-semibold mb-3">{t('Version history')}</h2><div className="flex flex-wrap gap-3">{versions.map(version=><Link key={version.id} className={version.id===c.id?'button-primary':'button-secondary'} href={`/admin/page-compositions/${version.id}`} aria-current={version.id===c.id?'page':undefined} onBefore={leave}>v{version.version_no} / {t(label(version.state))}</Link>)}</div></div>}
   {editable&&archivedSections.length>0&&<div><h2 className="font-semibold mb-3">{t('Archived sections')}</h2>{archivedSections.map(s=><div key={s.id} className="flex items-center gap-4 py-3"><span>{s.editor_label}</span><Action href={`/admin/page-compositions/${c.id}/sections/${s.id}/restore`} data={{lock_version:c.lock_version}}>{t('Restore')}</Action></div>)}</div>}
  </div></details>}
 </WorkspaceLayout>;
}
