[program:impact-ssr]
command=/usr/bin/node /var/www/impact/current/bootstrap/ssr/ssr.js
directory=/var/www/impact/current
environment=NODE_ENV="production",INERTIA_SSR_PORT="13714"
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/log/supervisor/impact-ssr.log
stopwaitsecs=10
