[program:impact-default]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/impact/current/artisan queue:work redis --queue=default,notifications,publishing --sleep=2 --tries=3 --timeout=120
directory=/var/www/impact/current
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/supervisor/impact-default.log
stopwaitsecs=3600

[program:impact-media]
command=php /var/www/impact/current/artisan queue:work redis --queue=media --sleep=2 --tries=3 --timeout=240
directory=/var/www/impact/current
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/supervisor/impact-media.log
stopwaitsecs=3600

[program:impact-search]
command=php /var/www/impact/current/artisan queue:work redis --queue=search --sleep=2 --tries=3 --timeout=120
directory=/var/www/impact/current
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/impact-search.log
stopwaitsecs=3600
