// Generates every vector deliverable and the data file the presentation consumes.
//   assets/logos/     full-colour emblem + horizontal + vertical for each concept
//   assets/variants/  every official variant of every layout
//   assets/js/brand-data.js
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { CONCEPTS } from './logos.mjs';
import { VARIANTS, BRAND } from './palette.mjs';
import { composeSvg } from './render.mjs';
import { buildLayouts } from './layouts.mjs';
import { ORG_NAME, TITLES } from './copy.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const out = (...p) => path.join(root, ...p);
const slug = (c) => `${String(c.number).padStart(2, '0')}-${c.key}`;

fs.rmSync(out('assets/logos'), { recursive: true, force: true });
fs.rmSync(out('assets/variants'), { recursive: true, force: true });
fs.mkdirSync(out('assets/logos'), { recursive: true });
fs.mkdirSync(out('assets/js'), { recursive: true });

const layouts = buildLayouts();
const LAYOUT_KEYS = ['emblem', 'horizontal', 'vertical'];
const data = { palette: BRAND, variants: {}, layouts, concepts: [], titles: TITLES };
for (const [k, v] of Object.entries(VARIANTS)) data.variants[k] = v;

let count = 0;
for (const c of CONCEPTS) {
  const art = c.build();
  data.concepts.push({ key: c.key, number: c.number, name: c.name, short: c.short, slug: slug(c), parts: art.shapes });
  for (const lk of LAYOUT_KEYS) {
    for (const [vk, pal] of Object.entries(VARIANTS)) {
      const meta = {
        title: `${c.name} — ${ORG_NAME}`,
        desc: `${VARIANTS[vk].label} ${lk} logo, concept ${c.number}: ${c.name}.`,
      };
      const svg = composeSvg(layouts[lk], art.shapes, pal, meta);
      const dir = out('assets/variants', slug(c));
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, `${lk}-${vk}.svg`), svg);
      if (vk === 'full-color') fs.writeFileSync(out('assets/logos', `${slug(c)}-${lk}.svg`), svg);
      count += 1;
    }
  }
}

const js = `/* Generated by src/build-assets.mjs — do not edit by hand. */
window.TVET_BRAND = ${JSON.stringify(data)};
window.TVET_BRAND.compose = ${composeSvg.toString().replace(/^export\s+/, '')};
`;
fs.writeFileSync(out('assets/js/brand-data.js'), js);
console.log(`Wrote ${count} SVG files and assets/js/brand-data.js (${(js.length / 1024).toFixed(0)} KB)`);
