<?php

declare(strict_types=1);

namespace App\Models;

use App\Models\Concerns\HasBinaryUuid;
use Illuminate\Database\Eloquent\Model;

abstract class BaseModel extends Model
{
    use HasBinaryUuid;

    /**
     * UUIDv7 identities are generated by the model and must never be accepted
     * from request-derived mass-assignment payloads.
     *
     * @var list<string>
     */
    protected $guarded = ['id'];
}
