import { Head, Link, usePage } from '@inertiajs/react';
import { AnimatePresence, motion } from 'framer-motion';
import { useEffect, useRef, useState } from 'react';
import { Action, useWorkspace } from '../Components/Workspace/UI';
import Icon from '../Components/Icon';
const links = [['content.view','Content','/admin/content'],['experts.manage','Experts','/admin/experts'],['pages.view','Page compositions','/admin/page-compositions'],['navigation.manage','Navigation and footer','/admin/navigation'],['engagement.view','Engagement','/admin/engagement'],['applications.view','Applications','/admin/applications'],['media.view','Media library','/admin/media'],['users.view','Users','/admin/users'],['roles.manage','Roles and permissions','/admin/roles'],['settings.manage','Settings Center','/admin/settings'],['audit.view','Audit log','/admin/audit-events']];
export default function WorkspaceLayout({ title, description, actions, children }) {
 const { t, can, user, privileged, identity, flash, sidebarDefault }=useWorkspace(); const { url }=usePage();
 const [open,setOpen]=useState(false); const [collapsed,setCollapsed]=useState(sidebarDefault==='collapsed'); const panel=useRef(null); const opener=useRef(null);
 useEffect(()=>{setOpen(false);},[url]);
 useEffect(()=>{if(!open)return;const before=document.activeElement;panel.current?.querySelector('button,a')?.focus();const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=previous;before?.focus();};},[open]);
 const nav=<><Link href="/" className="flex items-center gap-3 p-4 font-bold"><span className="brand-mark">I</span>{identity?.short_name}</Link><nav aria-label={t('Administration')} className="grid gap-1 p-3"><Link className="admin-nav-link" href={privileged ? '/admin' : '/dashboard'}>{t('Dashboard')}</Link>{links.filter(([permission])=>can(permission)).map(([,text,href])=><Link className="admin-nav-link" key={href} href={href} aria-current={url.split('?')[0]===href ? 'page' : undefined}>{t(text)}</Link>)}<Link className="admin-nav-link" href="/profile">{t('Profile')}</Link></nav><div className="p-4 border-t border-edge"><p className="text-sm mb-3">{user?.name}</p><Action href="/logout">{t('Log out')}</Action></div></>;
 const keydown=e=>{if(e.key==='Escape'){setOpen(false);opener.current?.focus();}if(e.key==='Tab'){const all=[...panel.current.querySelectorAll('a[href],button:not([disabled])')];const first=all[0],last=all.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};
 return <><Head><title>{t(title)} - {identity?.short_name}</title><meta head-key="robots" name="robots" content="noindex,nofollow,noarchive" /></Head><a className="skip-link" href="#admin-main-content">{t('Skip to content')}</a><div className="min-h-screen bg-quiet lg:flex"><aside className={`${collapsed?'lg:w-20':'lg:w-64'} hidden lg:flex shrink-0 flex-col border-e border-edge bg-white`}><button className="button-tertiary m-3" onClick={()=>setCollapsed(!collapsed)} aria-label={t('Toggle navigation')} aria-expanded={!collapsed}><Icon name="menu" /></button>{!collapsed&&nav}</aside><div className="min-w-0 flex-1"><header className="flex items-center justify-between border-b border-edge bg-white px-5 py-3"><button ref={opener} className="icon-button lg:hidden" onClick={()=>setOpen(true)} aria-label={t('Open menu')} aria-expanded={open}><Icon name="menu" /></button><span className="text-sm font-bold">{t('Protected workspace')}</span><Link className="text-link" href="/">{t('View website')}</Link></header><div className="admin-page-header"><div><p className="eyebrow">{t('Administration')}</p><h1 className="heading-2 mt-2">{t(title)}</h1>{description&&<p className="mt-3 text-muted">{t(description)}</p>}</div>{actions&&<div className="mt-4 flex flex-wrap gap-3">{actions}</div>}</div><main id="admin-main-content" tabIndex={-1} className="admin-workspace grid gap-6">{flash.status&&<div className="status-success" role="status">{t(flash.status)}</div>}{children}</main></div></div><AnimatePresence>{open&&<motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-50 bg-black/40" onClick={()=>setOpen(false)}><motion.div ref={panel} role="dialog" aria-modal="true" aria-label={t('Navigation')} onKeyDown={keydown} onClick={e=>e.stopPropagation()} initial={{x:-300}} animate={{x:0}} exit={{x:-300}} transition={{type:'spring',stiffness:320,damping:32}} className="h-full w-80 max-w-full overflow-y-auto bg-white"><button className="button-secondary m-4" onClick={()=>setOpen(false)}>{t('Close menu')}</button>{nav}</motion.div></motion.div>}</AnimatePresence></>;
}
